buildscript {
    repositories {
        def buildOnlyRepository = file("local-maven")
        if (buildOnlyRepository.exists()) {
            maven { url = buildOnlyRepository.toURI() }
        }
        maven { url = uri("https://dl.google.com/android/maven2/") }
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:9.1.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.21"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.3.21"
    }
}
