from pathlib import Path
import re

p = Path('app/src/main/java/es/david/rumbo/ui/App.kt')
s = p.read_text()

def one(old, new):
    global s
    if old not in s:
        raise SystemExit('missing marker: ' + old[:100])
    s = s.replace(old, new, 1)

# Home screen search state: exactly the three canonical food filters.
one('''    var searchFilter by rememberSaveable { mutableStateOf(CatalogFilter.ALL) }\n    var searchCategoryName by rememberSaveable { mutableStateOf<String?>(null) }\n    val searchCategory = searchCategoryName?.let { name ->\n        FoodCategory.entries.firstOrNull { it.name == name }\n    }\n    var searchCulinaryTypeName by rememberSaveable { mutableStateOf<String?>(null) }\n    val searchCulinaryType = searchCulinaryTypeName?.let { name ->\n        CulinaryType.entries.firstOrNull { it.name == name }\n    }\n''', '''    var searchRetailer by rememberSaveable { mutableStateOf<String?>(null) }\n    var searchNutritionalRole by rememberSaveable { mutableStateOf<String?>(null) }\n    var searchCulinaryRole by rememberSaveable { mutableStateOf<String?>(null) }\n''')

one('''                filter = searchFilter,\n                onFilterChange = { searchFilter = it },\n                categoryFilter = searchCategory,\n                onCategoryFilterChange = { searchCategoryName = it?.name },\n                culinaryTypeFilter = searchCulinaryType,\n                onCulinaryTypeFilterChange = { searchCulinaryTypeName = it?.name },\n''', '''                retailerFilter = searchRetailer,\n                onRetailerFilterChange = { searchRetailer = it },\n                nutritionalRoleFilter = searchNutritionalRole,\n                onNutritionalRoleFilterChange = { searchNutritionalRole = it },\n                culinaryRoleFilter = searchCulinaryRole,\n                onCulinaryRoleFilterChange = { searchCulinaryRole = it },\n''')

# HomeCatalogSearch signature.
one('''    textFieldState: TextFieldState,\n    filter: CatalogFilter, onFilterChange: (CatalogFilter) -> Unit,\n    categoryFilter: FoodCategory?, onCategoryFilterChange: (FoodCategory?) -> Unit,\n    culinaryTypeFilter: CulinaryType?,\n    onCulinaryTypeFilterChange: (CulinaryType?) -> Unit,\n''', '''    textFieldState: TextFieldState,\n    retailerFilter: String?, onRetailerFilterChange: (String?) -> Unit,\n    nutritionalRoleFilter: String?, onNutritionalRoleFilterChange: (String?) -> Unit,\n    culinaryRoleFilter: String?, onCulinaryRoleFilterChange: (String?) -> Unit,\n''')

# Add option lists after foodsById.
one('''    val foodsById = remember(foods) { foods.associateBy { it.id } }\n    val suggestionsByFoodId = remember(foodSuggestions) {\n''', '''    val foodsById = remember(foods) { foods.associateBy { it.id } }\n    val retailerOptions = remember(foods) { foods.flatMap { it.retailerValues() }.distinct().sorted() }\n    val nutritionalRoleOptions = remember(foods) {\n        foods.flatMap { it.nutritionalRoles }.distinct().sortedBy(::nutritionalRoleLabel)\n    }\n    val culinaryRoleOptions = remember(foods) {\n        foods.flatMap { it.culinaryRoles }.distinct().sortedBy(::culinaryRoleLabel)\n    }\n    val suggestionsByFoodId = remember(foodSuggestions) {\n''')

# Replace Home entries block wholesale until leaveForDetail.
pat = re.compile(r'''    val entries = remember\(\n        foods, dishes, normalized, filter, categoryFilter, culinaryTypeFilter, repertoireFoodIds,\n        foodSuggestions, suggestionsByFoodId, topSuggestionIds, personalizedScores\n    \) \{.*?\n    \}\n\n    val leaveForDetail =''', re.S)
replacement = '''    val entries = remember(\n        foods, dishes, normalized, retailerFilter, nutritionalRoleFilter, culinaryRoleFilter,\n        repertoireFoodIds, foodSuggestions, suggestionsByFoodId, topSuggestionIds, personalizedScores\n    ) {\n        buildList {\n            foods.forEach { food ->\n                val searchText = normalizeSearch(\n                    listOfNotNull(food.name, food.brand, food.barcode, food.retailer).joinToString(" ")\n                )\n                val suggested = food.id in topSuggestionIds\n                val matchesFilters =\n                    (retailerFilter == null || retailerFilter in food.retailerValues()) &&\n                    (nutritionalRoleFilter == null || nutritionalRoleFilter in food.nutritionalRoles) &&\n                    (culinaryRoleFilter == null || culinaryRoleFilter in food.culinaryRoles)\n                if (matchesFilters &&\n                    (normalized.isBlank() && (suggested || food.id in repertoireFoodIds) ||\n                        normalized.isNotBlank() && matchesSearch(searchText, normalized))) {\n                    add(CatalogEntry(food.id, food.name, false))\n                }\n            }\n            if (retailerFilter == null && nutritionalRoleFilter == null && culinaryRoleFilter == null) {\n                dishes.forEach { dish ->\n                    val favorite = dish.ingredients.any { it.foodId in repertoireFoodIds }\n                    if (normalized.isBlank() && favorite ||\n                        normalized.isNotBlank() && matchesSearch(normalizeSearch(dish.name), normalized)) {\n                        add(CatalogEntry(dish.id, dish.name, true))\n                    }\n                }\n            }\n        }.sortedWith(\n            if (normalized.isBlank()) {\n                compareBy<CatalogEntry> {\n                    if (it.isDish) Int.MAX_VALUE\n                    else foodSuggestions.indexOfFirst { suggestion -> suggestion.food.id == it.id }\n                        .takeIf { index -> index >= 0 } ?: Int.MAX_VALUE\n                }.thenByDescending {\n                    if (it.isDish) Double.NEGATIVE_INFINITY\n                    else suggestionsByFoodId[it.id]?.score ?: Double.NEGATIVE_INFINITY\n                }.thenBy { it.name.lowercase() }\n            } else {\n                compareBy<CatalogEntry> { searchMatchRank(it.name, normalized) }\n                    .thenByDescending {\n                        if (it.isDish) Double.NEGATIVE_INFINITY\n                        else personalizedScores[it.id] ?: Double.NEGATIVE_INFINITY\n                    }.thenByDescending {\n                        if (it.isDish) Double.NEGATIVE_INFINITY\n                        else suggestionsByFoodId[it.id]?.score ?: Double.NEGATIVE_INFINITY\n                    }.thenBy { it.name.lowercase() }\n            }\n        )\n    }\n\n    val leaveForDetail ='''
s, n = pat.subn(replacement, s, 1)
if n != 1:
    raise SystemExit(f'home entries block matches={n}')

# Header: exactly same three menus.
one('''                            CatalogFilterMenu(filter, onFilterChange)\n                            CatalogCategoryMenu(categoryFilter, onCategoryFilterChange)\n                            CatalogCulinaryTypeMenu(\n                                culinaryTypeFilter,\n                                onCulinaryTypeFilterChange\n                            )\n''', '''                            CatalogCanonicalFilterRow(\n                                retailerFilter, onRetailerFilterChange, retailerOptions,\n                                nutritionalRoleFilter, onNutritionalRoleFilterChange, nutritionalRoleOptions,\n                                culinaryRoleFilter, onCulinaryRoleFilterChange, culinaryRoleOptions\n                            )\n''')

p.write_text(s)
print('Home search now uses only retailer/nutritional-role/culinary-role filters')
