from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from urllib.parse import unquote

SOURCE = "CARREFOUR_FIRST_PARTY"
EAN_RE = re.compile(r"item_ean~v1(\d{8,14})", re.I)


def read_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    if not path.exists():
        return rows
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            value = json.loads(line)
        except Exception:
            continue
        if isinstance(value, dict):
            rows.append(value)
    return rows


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.write_text(
        "".join(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )


def valid_gtin(value: str) -> bool:
    if not re.fullmatch(r"\d{8}|\d{12,14}", value):
        return False
    digits = [int(c) for c in value]
    check = digits.pop()
    total = 0
    weight = 3
    for digit in reversed(digits):
        total += digit * weight
        weight = 1 if weight == 3 else 3
    return (10 - total % 10) % 10 == check


def main() -> int:
    ap = argparse.ArgumentParser(description="Extract public GTIN product identifiers observed during Carrefour page capture.")
    ap.add_argument("directory")
    args = ap.parse_args()

    directory = Path(args.directory)
    products_path = directory / "products.jsonl"
    evidence_path = directory / "field_evidence.jsonl"
    network_path = directory / "network_responses.jsonl"

    products = read_jsonl(products_path)
    evidence = read_jsonl(evidence_path)
    network = read_jsonl(network_path)
    by_sku = {str(row.get("retailer_sku")): row for row in products if row.get("retailer_sku")}

    observed: dict[str, set[str]] = {}
    for item in network:
        sku = item.get("retailer_sku")
        if not sku:
            continue
        decoded = unquote(str(item.get("url") or ""))
        for match in EAN_RE.finditer(decoded):
            value = match.group(1)
            if valid_gtin(value):
                observed.setdefault(str(sku), set()).add(value)

    added = 0
    conflicts = 0
    for sku, values in sorted(observed.items()):
        row = by_sku.get(sku)
        if not row or row.get("fetch_error") or len(values) != 1:
            if row and not row.get("fetch_error") and len(values) != 1:
                conflicts += 1
            continue
        value = next(iter(values))
        current = str(row.get("gtin") or "").strip()
        if current:
            if current != value:
                conflicts += 1
            continue
        row["gtin"] = value
        evidence.append({
            "retailer_sku": sku,
            "field": "gtin",
            "value": value,
            "source": SOURCE,
            "evidence_type": "OBSERVED_PRODUCT_PAGE_CLIENT_DATA",
            "source_url": row.get("canonical_url"),
            "observed_at": row.get("observed_at"),
            "provenance_note": "Checksum-valid GTIN observed in public client data generated by the same official Carrefour product page during capture.",
        })
        added += 1

    write_jsonl(products_path, products)
    write_jsonl(evidence_path, evidence)

    summary_path = directory / "summary.json"
    if summary_path.exists():
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        count = sum(bool(row.get("gtin")) for row in products)
        total = len(products)
        summary.setdefault("coverage", {})["gtin"] = {
            "count": count,
            "pct": round(100.0 * count / total, 2) if total else 0.0,
        }
        counts = summary.setdefault("counts", {})
        counts["evidence_rows"] = len(evidence)
        counts["gtin_from_official_page_client_data"] = added
        counts["gtin_client_data_conflicts"] = conflicts
        summary["gtin_provenance_note"] = (
            "GTIN values obtained from official page client data are labelled OBSERVED_PRODUCT_PAGE_CLIENT_DATA, not DECLARED."
        )
        summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps({
        "products": len(products),
        "network_rows": len(network),
        "skus_with_public_gtin": len(observed),
        "gtin_added": added,
        "conflicts": conflicts,
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
